version: "3.8"

services:
  backend:
    build: ./backend
    container_name: rag_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./backend/vector_db:/app/vector_db
      - ./backend/database:/app/database
      - ./backend/documents:/app/documents

  frontend:
    image: node:20-alpine
    container_name: rag_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
